//! Signal Infrastructure - Phase 11
//!
//! POSIX signal handling

pub mod types;

pub use types::{
    SigAction, SigSet, MAX_SIGNAL, SIGABRT, SIGALRM, SIGBUS, SIGCHLD, SIGCONT, SIGFPE, SIGHUP,
    SIGILL, SIGINT, SIGKILL, SIGPIPE, SIGQUIT, SIGSEGV, SIGSTKFLT, SIGSTOP, SIGTERM, SIGTRAP,
    SIGTSTP, SIGTTIN, SIGTTOU, SIGUSR1, SIGUSR2, SIG_BLOCK, SIG_SETMASK, SIG_UNBLOCK,
};
