#!/bin/bash

# Script d'initialisation pour Exo-OS
# Montage des systèmes de fichiers virtuels
mount -t proc none /proc
mount -t sysfs none /sys
mount -t devtmpfs none /dev

# Configuration réseau de base
ip link set lo up

# Démarrage des services essentiels
/etc/init.d/ia-core start
/etc/init.d/networking start
/etc/init.d/security start

# Lancement de l'interface utilisateur
/usr/bin/exo-ui
