[package]
name = "exo-bootloader"
version = "0.1.0"
edition = "2021"
authors = ["ExoOS Team"]

[dependencies]
# Utilise bootloader 0.9 pour compatibilité avec notre configuration
bootloader = { version = "0.9", features = ["map_physical_memory"] }

[lib]
name = "exo_bootloader"
path = "src/lib.rs"
