[package]
name = "exo-bootloader"
version = "0.1.0"
edition = "2021"
authors = ["ExoOS Team"]

[dependencies]
# Utilise bootloader 0.9 sans map_physical_memory pour éviter les conflits de mapping
bootloader = "0.9"

[lib]
name = "exo_bootloader"
path = "src/lib.rs"
